# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: D

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: dlang-community/setup-dlang@7c3e57bdc1ff2d8994f00e61b3ef400e67d2d7ac

    - name: 'Install openblas-dev'
      run: |
        sudo apt-get install libopenblas-dev

    - name: 'Build & Test'
      run: |
        dub build --compiler=$DC
        dub test --compiler=$DC

    - name: 'Build Examples'
      run: |
        cd ./examples
        cd ./xor
        dub build --compiler=$DC
        cd ../mnist
        dub build --compiler=$DC
